// Code generated by go-imbed. DO NOT EDIT.

// Package site holds binary resources embedded into Go executable
package site

import (
	"os"
	"io"
	"path/filepath"
	"io/ioutil"
	"strconv"
	"net/http"
	"strings"
	"path"
	"bytes"
	"compress/gzip"
	"time"
)

func blob_bytes(uint32) []byte
func blob_string(uint32) string

// Asset represents binary resource stored within Go executable. Asset implements
// fmt.Stringer and io.WriterTo interfaces, decompressing binary data if necessary.
type Asset struct {
	name         string // File name
	size         int32  // File size (uncompressed)
	blob         []byte // Resource blob []byte
	str_blob     string // Resource blob as string
	isCompressed bool   // true if resources was compressed with gzip
	mime         string // MIME Type
	tag          string // Tag is essentially a Tag of resource content and can be used as a value for "Etag" HTTP header
}

// Name returns the base name of the asset
func (a *Asset) Name() string       { return a.name }
// MimeType returns MIME Type of the asset
func (a *Asset) MimeType() string   { return a.mime }
// IsCompressed returns true of asset has been compressed
func (a *Asset) IsCompressed() bool { return a.isCompressed }

// Size implements os.FileInfo and returns the size of the asset (uncompressed, if asset has been compressed)
func (a *Asset) Size() int64        { return int64(a.size) }
// Mode implements os.FileInfo and always returns 0444
func (a *Asset) Mode() os.FileMode  { return 0444 }
// ModTime implements os.FileInfo and returns the time stamp when this package has been produced (the same value for all the assets)
func (a *Asset) ModTime() time.Time { return stamp }
// IsDir implements os.FileInfo and returns false
func (a *Asset) IsDir() bool        { return false }
// Sys implements os.FileInfo and returns nil
func (a *Asset) Sys() interface{}   { return nil }

// WriteTo implements io.WriterTo interface and writes content of the asset to w
func (a *Asset) WriteTo(w io.Writer) (int64, error) {
	if a.isCompressed {
		ungzip, _ := gzip.NewReader(bytes.NewReader(a.blob))
		defer ungzip.Close()
		return io.Copy(w, ungzip)
	}
	n, err := w.Write(a.blob)
	return int64(n), err
}

// The CopyTo method copies asset content to the target directory.
// If file with the same name, size and modification time exists,
// it will not be overwritten, unless overwrite = true is specified.
func (a *Asset) CopyTo(target string, mode os.FileMode, overwrite bool) error {
	fname := filepath.Join(target, a.name)
	fs, err := os.Stat(fname)
	if err == nil {
		if fs.IsDir() {
			return os.ErrExist
		} else if !overwrite && fs.Size() == a.Size() && fs.ModTime().Equal(a.ModTime()) {
			return nil
		}
	}
	file, err := ioutil.TempFile(target, ".imbed")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	_, err = a.WriteTo(file)
	if err != nil {
		return err
	}
	file.Close()
	os.Chtimes(file.Name(), a.ModTime(), a.ModTime())
	os.Chmod(file.Name(), mode)
	return os.Rename(file.Name(), fname)
}

// String returns (uncompressed) content of asset as a string
func (a *Asset) String() string {
	if a.isCompressed {
		ungzip, _ := gzip.NewReader(bytes.NewReader(a.blob))
		ret, _ := ioutil.ReadAll(ungzip)
		ungzip.Close()
		return string(ret)
	}
	return a.str_blob
}

type assetReader struct {
	bytes.Reader
}

func (r *assetReader) Close() error {
	r.Reset(nil)
	return nil
}

// Opens asset as an io.ReadCloser. Returns os.ErrNotExist if no asset is found.
func Open(name string) (File, error) {
	return root.Open(name)
}

// Gets asset by name. Returns nil if no asset found.
func Get(name string) *Asset {
	if entry, ok := idx[name]; ok {
		return entry
	} else {
		return nil
	}
}

// Get asset by name. Panics if no asset found.
func Must(name string) *Asset {
	if entry, ok := idx[name]; ok {
		return entry
	} else {
		panic("asset " + name + " not found")
	}
}

type directoryAsset struct {
	name  string
	dirs  []directoryAsset
	files []Asset
}

var root *directoryAsset
type httpFileSystem struct {}

func (*httpFileSystem) Open(name string) (http.File, error) {
	return root.Open(name)
}

func HttpFileSystem() http.FileSystem {
	return &httpFileSystem{}
}

// A File is returned by virtual FileSystem's Open method.
// The methods should behave the same as those on an *os.File.
type File interface {
	io.Closer
	io.Reader
	io.Seeker
	Readdir(count int) ([]os.FileInfo, error)
	Stat() (os.FileInfo, error)
	// The CopyTo method copies file content to the target path.
	// If file with the same name, size and modification time exists,
	// it will not be overwritten, unless overwrite = true is specified.
	// site.Root().CopyTo(".", mode, false) will effectively
	// extract content of the filesystem to the current directory (which
	// makes it the most space-wise inefficient self-extracting archive
	// ever).
	CopyTo(target string, mode os.FileMode, overwrite bool) error
}

func (d *directoryAsset) Open(name string) (File, error) {
	if len(name) > 0 && name[0] == '/' {
		name = name[1:]
	}
	p := path.Clean(name)
	if p == "." {
		return &directoryAssetFile{dir: d}, nil
	} else {
		var first, rest string
		i := strings.IndexByte(p, '/')
		if i == -1 {
			first = p
		} else {
			first = p[:i]
			rest = p[i+1:]
		}
		for j := range d.dirs {
			if d.dirs[j].name == first {
				if rest == "" {
					return &directoryAssetFile{dir: &d.dirs[j]}, nil
				} else {
					return d.dirs[j].Open(rest)
				}
			}
		}
		if rest != "" {
			return nil, os.ErrNotExist
		}
		for j := range d.files {
			if d.files[j].name == first {
				if d.files[j].isCompressed {
					ret := &assetCompressedFile{asset: &d.files[j]}
					ret.Reset(bytes.NewReader(d.files[j].blob))
					return ret, nil
				} else {
					ret := &assetFile{asset: &d.files[j]}
					ret.Reset(d.files[j].blob)
					return ret, nil
				}
			}
		}
		return nil, os.ErrNotExist
	}
}

type directoryAssetFile struct {
	dir *directoryAsset
	pos int
}

func (d *directoryAssetFile) Close() error {
	if d.pos < 0 {
		return os.ErrClosed
	}
	d.pos = -1
	return nil
}

func (d *directoryAssetFile) Read([]byte) (int, error) {
	if d.pos < 0 {
		return 0, os.ErrClosed
	}
	return 0, io.EOF
}

func (d *directoryAssetFile) Stat() (os.FileInfo, error) {
	if d.pos < 0 {
		return nil, os.ErrClosed
	}
	return d.dir, nil
}

func (d *directoryAssetFile) Seek(pos int64, whence int) (int64, error) {
	if d.pos < 0 {
		return 0, os.ErrClosed
	}
	if whence == io.SeekStart && pos == 0 {
		d.pos = 0
		return 0, nil
	} else {
		return 0, os.ErrInvalid
	}
}

func (d *directoryAssetFile) Readdir(count int) ([]os.FileInfo, error) {
	if d.pos < 0 {
		return nil, os.ErrClosed
	}
	ret := make([]os.FileInfo, len(d.dir.dirs) + len(d.dir.files))
	i := 0
	for j := range d.dir.dirs {
		ret[j + i] = &d.dir.dirs[j]
	}
	i = len(d.dir.dirs)
	for j := range d.dir.files {
		ret[j + i] = &d.dir.files[j]
	}
	if count <= 0 {
		return ret, nil
	} else if d.pos > len(ret) {
		return nil, io.EOF
	} else {
		return ret[d.pos:d.pos+count], nil
	}
}

func (d *directoryAsset) copyTo(target string, dirmode os.FileMode, mode os.FileMode, overwrite bool) error {
	dname := filepath.Join(target, d.name)
	err := os.MkdirAll(dname, dirmode)
	if err != nil {
		return err
	}
	for i := range d.dirs {
		if err = d.dirs[i].copyTo(dname, dirmode, mode, overwrite); err != nil {
			return err
		}
	}
	for i := range d.files {
		if err = d.files[i].CopyTo(dname, mode, overwrite); err != nil {
			return err
		}
	}
	return nil
}

func (d *directoryAssetFile) CopyTo(target string, mode os.FileMode, overwrite bool) error {
	dirmode := ((mode&0444)>>2)|mode
	return d.dir.copyTo(target, dirmode, mode, overwrite)
}

func (d *directoryAsset) Name() string       { return d.name }
func (d *directoryAsset) Size() int64        { return 0 }
func (d *directoryAsset) Mode() os.FileMode  { return os.ModeDir | 0555 }
func (d *directoryAsset) ModTime() time.Time { return stamp }
func (d *directoryAsset) IsDir() bool        { return true }
func (d *directoryAsset) Sys() interface{}   { return nil }

type assetFile struct {
	assetReader
	asset *Asset
}

func (a *assetFile) Stat() (os.FileInfo, error) {
	return a.asset, nil
}

func (a *assetFile) Readdir(int) ([]os.FileInfo, error) {
	return nil, os.ErrInvalid
}

func (a *assetFile) CopyTo(target string, mode os.FileMode, overwrite bool) error {
	return a.asset.CopyTo(target, mode, overwrite)
}
type assetCompressedFile struct {
	gzip.Reader
	asset *Asset
}

func (a *assetCompressedFile) Stat() (os.FileInfo, error) {
	return a.asset, nil
}

func (a *assetCompressedFile) Seek(int64, int) (int64, error) {
	return 0, os.ErrInvalid
}

func (a *assetCompressedFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, os.ErrInvalid
}

func (a *assetCompressedFile) CopyTo(target string, mode os.FileMode, overwrite bool) error {
	return a.asset.CopyTo(target, mode, overwrite)
}

var idx = make(map[string]*Asset)
var stamp time.Time

func init() {
	stamp = time.Unix(1515560467,887731000)
	bb := blob_bytes(66432)
	bs := blob_string(66432)
	root = &directoryAsset{
		dirs: []directoryAsset{
			{
				name: "css",
				files: []Asset{
					{
						name:         "style.css",
						blob:         bb[264:1348],
						str_blob:     bs[264:1348],
						mime:         "text/css; charset=utf-8",
						tag:          "zlyzclmjepcnm",
						size:         3213,
						isCompressed: true,
					},
				},
			},
			{
				name: "images",
				files: []Asset{
					{
						name:         "a-nice-picture.jpg",
						blob:         bb[1352:63866],
						str_blob:     bs[1352:63866],
						mime:         "image/jpeg",
						tag:          "ahaszqrnqpm2a",
						size:         62514,
						isCompressed: false,
					},
				},
			},
		},
		files: []Asset{
			{
				name:         "404.html",
				blob:         bb[0:258],
				str_blob:     bs[0:258],
				mime:         "text/html; charset=utf-8",
				tag:          "hrlex6jrmr43u",
				size:         359,
				isCompressed: true,
			},
			{
				name:         "index.html",
				blob:         bb[63872:66426],
				str_blob:     bs[63872:66426],
				mime:         "text/html; charset=utf-8",
				tag:          "kqf5n5qf7i6vu",
				size:         7752,
				isCompressed: true,
			},
		},
	}
	idx["css/style.css"] = &root.dirs[0].files[0]
	idx["images/a-nice-picture.jpg"] = &root.dirs[1].files[0]
	idx["404.html"] = &root.files[0]
	http404Asset = &root.files[0]
	idx["index.html"] = &root.files[1]
	idx[""] = &root.files[1]
}
var http404Asset *Asset
// ServeHTTP provides a convenience handler whenever embedded content should be served from the root URI.
var ServeHTTP = HTTPHandlerWithPrefix("")

// HTTPHandlerWithPrefix provides a simple way to serve embedded content via
// Go standard HTTP server and returns an http handler function. The "prefix"
// will be stripped from the request URL to serve embedded content from non-root URI
func HTTPHandlerWithPrefix(prefix string) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, req *http.Request) {
		if req.Method != "GET" && req.Method != "HEAD" {
			w.WriteHeader(http.StatusMethodNotAllowed)
			return
		}
		if !strings.HasPrefix(req.URL.Path, prefix) {
			http.NotFound(w, req)
			return
		}
		reqPath := req.URL.Path[len(prefix):]
		if strings.HasPrefix(reqPath, "/") {
			reqPath = reqPath[1:]
		}
		var status = http.StatusOK
		asset := Get(reqPath)
		if asset == nil {
			asset = http404Asset
			status = http.StatusNotFound
		}
		if tag := req.Header.Get("If-None-Match"); tag != "" {
			if strings.HasPrefix("W/", tag) || strings.HasPrefix("w/", tag) {
				tag = tag[2:]
			}
			if tag, err := strconv.Unquote(tag); err == nil && tag == asset.tag {
				w.WriteHeader(http.StatusNotModified)
				return
			}
		}
		if mtime := req.Header.Get("If-Modified-Since"); mtime != "" {
			if ts, err := time.Parse(time.RFC1123, mtime); err == nil && !ts.Before(stamp) {
				w.WriteHeader(http.StatusNotModified)
				return
			}
		}
		var deflate = asset.isCompressed
		if encs, ok := req.Header["Accept-Encoding"]; ok {
			for _, enc := range encs {
				if strings.Contains(enc, "gzip") {
					if deflate {
						w.Header().Set("Content-Encoding", "gzip")
					}
					deflate = false
					break
				}
			}
		}
		if !deflate {
			w.Header().Set("Content-Length", strconv.FormatInt(int64(len(asset.blob)), 10))
		}
		w.Header().Set("Content-Type", asset.mime)
		w.Header().Set("Etag", strconv.Quote(asset.tag))
		w.Header().Set("Last-Modified", stamp.Format(time.RFC1123))
		w.WriteHeader(status)
		if req.Method != "HEAD" {
			if deflate {
				ungzip, _ := gzip.NewReader(bytes.NewReader(asset.blob))
				defer ungzip.Close()
				io.Copy(w, ungzip)
			} else {
				w.Write(asset.blob)
			}
		}
	}
}

